### ISSUE TITLE
fs readfilesync is not a function

### ISSUE THREAD

**Issue by amlcodes** [cryptowatch/cw-sdk-node#1]
fs is being called from pjson 
also
  Error: ENOENT: no such file or directory, open '//package.json'

**Comment by wellsjo** [comment]
thanks for reporting. can you give steps to reproduce these issues? I'm able to use the client just fine.

**Comment by wellsjo** [comment]
I realized this is happening because you are transpiling to javascript - that won't work. I will try to get this browser friendly in the next version, but for now it's intended to be run with nodejs.

**Comment by amlcodes** [comment]
yeah of course, my bad! I figured that out a little too late. I would love a browser friendly version. So the approach to this is to just build an api with the the routes that use the sdk as needed, and returning the response to the browser

**Comment by wellsjo** [comment]
yeah, something like that will work. sorry that is annoying, I'll try to get browser support out soon.
