### ISSUE TITLE
How can I pass the Query Parameters to the RESTClient.getOHLC ?

### ISSUE THREAD

**Issue by SoftwareKim** [cryptowatch/cw-sdk-node#11]
There are the Query Parameters on your REST API document.
https://docs.cryptowat.ch/rest-api/markets/ohlc
![image](https://user-images.githubusercontent.com/61534893/75419423-21ba6500-5979-11ea-8f6d-f4e33b7644be.png)

How can I pass the Query Parameters to the RESTClient.getOHLC ?

**Comment by wellsjo** [comment]
`getOHLC` has `options` now which allows for specifying these params. closing.
