### ISSUE TITLE
Update documentation and strange behaviour

### ISSUE THREAD

**Issue by dsbaars** [cryptowatch/cw-sdk-node#18]
It seems there is a lot of documentation missing, I can't find what the stream `pairs:*:performance` does for example. 

Also I only get buy trades when subscribing to `:trades` (tried with `markets:247:trades`), sell orders are empty:
````
2020-06-06T11:24:27.570Z MARKET UPDATE {
  market: { id: 247, exchangeID: 16, currencyPairID: 175 },
  trades: []
}
2020-06-06T11:24:29.846Z MARKET UPDATE {
  market: { id: 247, exchangeID: 16, currencyPairID: 175 },
  trades: [
    {
      externalID: 'f8a19ec3-33ab-8191-6c9e-42acc5382619',
      timestamp: 2020-06-06T11:24:29.579Z,
      side: 'buy',
      price: '9673.5',
      amount: '1'
    }
  ]
}
````
And I experience the same as described in #14

**Comment by wellsjo** [comment]
the buy/sell orders should be fixed now. apologies about the `performance` subscription, that should be undocumented. I will remove that from the README.
