### ISSUE TITLE
How to get Real Time Market Data for DIfferent Markets ....

### ISSUE THREAD

**Issue by nettemNvest** [cryptowatch/cw-sdk-node#2]
subscriptions: [
    "markets:87:trades", // kraken btc:usd
    "pairs:9:performance", // btc/usd pair
    "markets:1:trades"
  ]

this gives Data for BTC  , how can i get the data for other currencies....

**Comment by wellsjo** [comment]
you can get the IDs for the market/pair/exchange you need from the API https://api.cryptowat.ch/. pretty soon the sdk will have a better api so you don't have to deal with IDs (coming soon).

**Comment by DBosley** [comment]
@nettemNvest The new beta release's `RESTClient` should help you out. There are methods on it which will allow you to retrieve the market and pair IDs (as well as other related data). You can install the beta by running the following NPM command:

`npm install cw-sdk-node@1.0.0-beta.1`
