### ISSUE TITLE
protobuf error

### ISSUE THREAD

**Issue by miguelcobain** [cryptowatch/cw-sdk-node#31]
I'm getting these errors while trying to use the library with TypeScript:

```
node_modules/cw-sdk-node/build/websocket/types/trading.d.ts:1:10 - error TS2305: Module '"../modules/proto"' has no exported member 'ProtobufBroker'.

1 import { ProtobufBroker } from '../modules/proto';
           ~~~~~~~~~~~~~~

node_modules/cw-sdk-node/build/websocket/WebSocketClient.d.ts:3:10 - error TS2305: Module '"./modules/proto"' has no exported member 'ProtobufClient'.

3 import { ProtobufClient } from './modules/proto';
           ~~~~~~~~~~~~~~
```

This happens because the file at `build/websocket/modules/proto/index.d.ts` is being overwritten by the type definitions file generation with the following contents:

```
export = $root;
declare var $root: {};
```

That's because typescript compiler doesn't find any types on the corresponding index.js file. 

Is this protobuf usage up to date?
Perhaps we should follow these instructions: https://github.com/protobufjs/protobuf.js#usage-with-typescript

**Comment by miguelcobain** [comment]
I see that the new pbjs has an option to generate a typescript file directly.
We should let it generate a typescript file and handle the definitions generation to the compiler!

https://github.com/evanw/pbjs

**Comment by DBosley** [comment]
@miguelcobain that link isn't the protobufjs package that we use. I'll look into it, but at a glance it doesn't look like the right one to use. The one we're using is here: https://github.com/protobufjs/protobuf.js

I'll double check the typescript usage though and see if there's anything I can to fix this.

**Comment by DBosley** [comment]
I found the issue, the d.ts file we generate for the proto files doesn't get automatically copied to the build folder after running `tsc`, this needs to be done manually. I've added a step to do so.

**Comment by miguelcobain** [comment]
I still get the same errors with `1.0.0-beta.8`:
```
node_modules/cw-sdk-node/build/websocket/types/trading.d.ts:1:10 - error TS2305: Module '"../modules/proto"' has no exported member 'ProtobufBroker'.

1 import { ProtobufBroker } from '../modules/proto';
           ~~~~~~~~~~~~~~

node_modules/cw-sdk-node/build/websocket/WebSocketClient.d.ts:3:10 - error TS2305: Module '"./modules/proto"' has no exported member 'ProtobufClient'.

3 import { ProtobufClient } from './modules/proto';
           ~~~~~~~~~~~~~~
```

So, the first error is basically telling us that 
Here is the content of the file at we couldn't not import any `ProtobufBroker` from `../modules/proto`. And indeed, when I check the contents of the file at `./node_modules/cw-sdk-node/build/websocket/modules/proto/index.d.ts` I found this:

```typescript
export = $root;
declare var $root: {};
```

**Comment by sglyon** [comment]
running in to this today based on v1.0.0-beta.8

**Comment by durek1337** [comment]
same in 1.0.0-beta9
I use 0.0.2 now, the example of https://docs.cryptowat.ch/websocket-api/
seems to work with this downgrade.
