### ISSUE TITLE
Is it possible to create orders with this API?

### ISSUE THREAD

**Issue by ShravanSunder** [cryptowatch/cw-sdk-node#40]
I didn't see this on the docs, but is it possible to create orders with this API?  I'm looking create orders on kraken based on market data.  For example i'd like to make orders based on SMA and EMA.

Additionally, is it possible to enable discussions on this project to encourage sharing?

**Comment by wellsjo** [comment]
trading functionality isn't currently available, but is planned and coming soon.

**Comment by ShravanSunder** [comment]
thanks!
